[2025-03-13T06:02:31.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T06:02:31.418+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_product_analysis.customers scheduled__2025-03-12T00:00:00+00:00 [queued]>
[2025-03-13T06:02:31.513+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_product_analysis.customers scheduled__2025-03-12T00:00:00+00:00 [queued]>
[2025-03-13T06:02:31.515+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-13T06:02:31.697+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): customers> on 2025-03-12 00:00:00+00:00
[2025-03-13T06:02:31.739+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T06:02:31.768+0000] {standard_task_runner.py:72} INFO - Started process 2016 to run task
[2025-03-13T06:02:31.759+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_product_analysis', 'customers', 'scheduled__2025-03-12T00:00:00+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpmp063qn0']
[2025-03-13T06:02:31.774+0000] {standard_task_runner.py:105} INFO - Job 500: Subtask customers
[2025-03-13T06:02:32.108+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_product_analysis.customers scheduled__2025-03-12T00:00:00+00:00 [running]> on host b404e9833d11
[2025-03-13T06:02:32.576+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_product_analysis' AIRFLOW_CTX_TASK_ID='customers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T00:00:00+00:00'
[2025-03-13T06:02:32.589+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T06:02:32.591+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T06:02:32.604+0000] {logging_mixin.py:190} INFO - Current task name:customers state:running start_date:2025-03-13 06:02:31.435428+00:00
[2025-03-13T06:02:32.624+0000] {logging_mixin.py:190} INFO - Dag name:daily_product_analysis and current dag run status:running
[2025-03-13T06:02:32.640+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T06:02:33.810+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-13T06:02:34.316+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1445 customer records.
[2025-03-13T06:02:34.322+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-13T06:02:34.374+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T06:02:34.410+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_product_analysis, task_id=customers, run_id=scheduled__2025-03-12T00:00:00+00:00, execution_date=20250312T000000, start_date=20250313T060231, end_date=20250313T060234
[2025-03-13T06:02:34.590+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-13T06:02:34.639+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-13T06:02:34.670+0000] {logging_mixin.py:190} INFO - Dag name:daily_product_analysis queued_at:2025-03-13 06:02:11.989705+00:00
[2025-03-13T06:02:34.679+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-13T06:02:34.756+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T06:02:34.791+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
