[2025-03-12T15:05:47.828+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:05:47.873+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.order_items scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:47.894+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.order_items scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:47.895+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:05:47.933+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): order_items> on 2025-03-05 13:00:00+00:00
[2025-03-12T15:05:47.942+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1342) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T15:05:47.945+0000] {standard_task_runner.py:72} INFO - Started process 1350 to run task
[2025-03-12T15:05:47.945+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'order_items', 'scheduled__2025-03-05T13:00:00+00:00', '--job-id', '493', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmp47sx0558']
[2025-03-12T15:05:47.948+0000] {standard_task_runner.py:105} INFO - Job 493: Subtask order_items
[2025-03-12T15:05:48.035+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.order_items scheduled__2025-03-05T13:00:00+00:00 [running]> on host b404e9833d11
[2025-03-12T15:05:48.174+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='order_items' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T13:00:00+00:00'
[2025-03-12T15:05:48.176+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T15:05:48.177+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T15:05:48.178+0000] {logging_mixin.py:190} INFO - Current task name:order_items state:running start_date:2025-03-12 15:05:47.874037+00:00
[2025-03-12T15:05:48.179+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T15:05:48.180+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:05:49.178+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-12T15:05:54.258+0000] {logging_mixin.py:190} INFO - Validation successful. Found 4722 order item records.
[2025-03-12T15:05:54.259+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:05:54.275+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:05:54.276+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=order_items, run_id=scheduled__2025-03-05T13:00:00+00:00, execution_date=20250305T130000, start_date=20250312T150547, end_date=20250312T150554
[2025-03-12T15:05:54.325+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T15:05:54.327+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T15:05:54.328+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-12 15:04:59.119982+00:00
[2025-03-12T15:05:54.329+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-12T15:05:54.383+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:05:54.442+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:05:54.446+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
