[2025-03-11T09:10:06.659+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T09:10:07.212+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.orders manual__2025-03-11T09:09:41.505828+00:00 [queued]>
[2025-03-11T09:10:07.258+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.orders manual__2025-03-11T09:09:41.505828+00:00 [queued]>
[2025-03-11T09:10:07.270+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T09:10:07.355+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): orders> on 2025-03-11 09:09:41.505828+00:00
[2025-03-11T09:10:07.384+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8200) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T09:10:07.392+0000] {standard_task_runner.py:72} INFO - Started process 8216 to run task
[2025-03-11T09:10:07.393+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'orders', 'manual__2025-03-11T09:09:41.505828+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/validate_all_tables_dag.py', '--cfg-path', '/tmp/tmp2iixykrf']
[2025-03-11T09:10:07.397+0000] {standard_task_runner.py:105} INFO - Job 228: Subtask orders
[2025-03-11T09:10:07.555+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.orders manual__2025-03-11T09:09:41.505828+00:00 [running]> on host efacfdd0be48
[2025-03-11T09:10:07.939+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T09:09:41.505828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T09:09:41.505828+00:00'
[2025-03-11T09:10:07.950+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T09:10:07.958+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T09:10:07.961+0000] {logging_mixin.py:190} INFO - Current task name:orders state:running start_date:2025-03-11 09:10:07.213989+00:00
[2025-03-11T09:10:07.968+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-11T09:10:07.977+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T09:10:08.081+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-11T09:10:08.083+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T09:10:08.123+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T09:10:08.124+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=orders, run_id=manual__2025-03-11T09:09:41.505828+00:00, execution_date=20250311T090941, start_date=20250311T091007, end_date=20250311T091008
[2025-03-11T09:10:08.196+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T09:10:08.198+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T09:10:08.200+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-11 09:09:41.563044+00:00
[2025-03-11T09:10:08.203+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-11T09:10:08.237+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T09:10:08.353+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-11T09:10:08.371+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
