[2025-03-11T09:17:36.927+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T09:17:37.116+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.customers manual__2025-03-11T09:17:10.388824+00:00 [queued]>
[2025-03-11T09:17:37.216+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.customers manual__2025-03-11T09:17:10.388824+00:00 [queued]>
[2025-03-11T09:17:37.418+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-11T09:17:37.709+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): customers> on 2025-03-11 09:17:10.388824+00:00
[2025-03-11T09:17:37.789+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8299) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T09:17:37.795+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'customers', 'manual__2025-03-11T09:17:10.388824+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/validate_all_tables_dag.py', '--cfg-path', '/tmp/tmp9bcrkjkf']
[2025-03-11T09:17:37.805+0000] {standard_task_runner.py:72} INFO - Started process 8314 to run task
[2025-03-11T09:17:37.837+0000] {standard_task_runner.py:105} INFO - Job 232: Subtask customers
[2025-03-11T09:17:40.563+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.customers manual__2025-03-11T09:17:10.388824+00:00 [running]> on host efacfdd0be48
[2025-03-11T09:17:41.466+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='customers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T09:17:10.388824+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T09:17:10.388824+00:00'
[2025-03-11T09:17:41.500+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T09:17:41.515+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T09:17:41.529+0000] {logging_mixin.py:190} INFO - Current task name:customers state:running start_date:2025-03-11 09:17:37.163758+00:00
[2025-03-11T09:17:41.561+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-11T09:17:41.624+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T09:17:42.897+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1445 customer records.
[2025-03-11T09:17:43.071+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-11T09:17:43.215+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T09:17:43.250+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=customers, run_id=manual__2025-03-11T09:17:10.388824+00:00, execution_date=20250311T091710, start_date=20250311T091737, end_date=20250311T091743
[2025-03-11T09:17:43.808+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-11T09:17:43.835+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-11T09:17:43.850+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-11 09:17:10.479662+00:00
[2025-03-11T09:17:43.867+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-11T09:17:45.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-11T09:17:45.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
