[2025-03-12T15:05:24.781+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T15:05:24.966+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.stores scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:25.018+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.stores scheduled__2025-03-05T13:00:00+00:00 [queued]>
[2025-03-12T15:05:25.056+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T15:05:25.203+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): stores> on 2025-03-05 13:00:00+00:00
[2025-03-12T15:05:25.255+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'stores', 'scheduled__2025-03-05T13:00:00+00:00', '--job-id', '480', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmphqlntjoc']
[2025-03-12T15:05:25.266+0000] {standard_task_runner.py:105} INFO - Job 480: Subtask stores
[2025-03-12T15:05:25.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T15:05:25.311+0000] {standard_task_runner.py:72} INFO - Started process 1298 to run task
[2025-03-12T15:05:25.734+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.stores scheduled__2025-03-05T13:00:00+00:00 [running]> on host b404e9833d11
[2025-03-12T15:05:26.392+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='stores' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-05T13:00:00+00:00'
[2025-03-12T15:05:26.407+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T15:05:26.437+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T15:05:26.453+0000] {logging_mixin.py:190} INFO - Current task name:stores state:running start_date:2025-03-12 15:05:24.993767+00:00
[2025-03-12T15:05:26.456+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T15:05:26.469+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T15:05:29.744+0000] {httpchecksum.py:481} INFO - Skipping checksum validation. Response did not contain one of the following algorithms: ['crc32', 'sha1', 'sha256'].
[2025-03-12T15:05:29.785+0000] {logging_mixin.py:190} INFO - Validation successful. Found 3 store records.
[2025-03-12T15:05:29.787+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T15:05:29.821+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T15:05:29.823+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=stores, run_id=scheduled__2025-03-05T13:00:00+00:00, execution_date=20250305T130000, start_date=20250312T150524, end_date=20250312T150529
[2025-03-12T15:05:29.884+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T15:05:29.885+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T15:05:29.886+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-12 15:04:59.119982+00:00
[2025-03-12T15:05:29.887+0000] {logging_mixin.py:190} INFO - Task hostname:b404e9833d11 operator:PythonOperator
[2025-03-12T15:05:29.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T15:05:30.028+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T15:05:30.034+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
