[2025-03-12T08:09:13.492+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T08:09:13.905+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_category_analysis.orders manual__2025-03-12T08:08:41.718880+00:00 [queued]>
[2025-03-12T08:09:13.938+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_category_analysis.orders manual__2025-03-12T08:08:41.718880+00:00 [queued]>
[2025-03-12T08:09:13.940+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-12T08:09:14.079+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): orders> on 2025-03-12 08:08:41.718880+00:00
[2025-03-12T08:09:14.115+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weekly_category_analysis', 'orders', 'manual__2025-03-12T08:08:41.718880+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/data/scheduled.py', '--cfg-path', '/tmp/tmpib3imns9']
[2025-03-12T08:09:14.113+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T08:09:14.125+0000] {standard_task_runner.py:105} INFO - Job 333: Subtask orders
[2025-03-12T08:09:14.127+0000] {standard_task_runner.py:72} INFO - Started process 747 to run task
[2025-03-12T08:09:14.376+0000] {task_command.py:467} INFO - Running <TaskInstance: weekly_category_analysis.orders manual__2025-03-12T08:08:41.718880+00:00 [running]> on host fc342882eb4f
[2025-03-12T08:09:14.725+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_category_analysis' AIRFLOW_CTX_TASK_ID='orders' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T08:08:41.718880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T08:08:41.718880+00:00'
[2025-03-12T08:09:14.731+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T08:09:14.738+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T08:09:14.755+0000] {logging_mixin.py:190} INFO - Current task name:orders state:running start_date:2025-03-12 08:09:13.907354+00:00
[2025-03-12T08:09:14.757+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis and current dag run status:running
[2025-03-12T08:09:14.758+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T08:09:14.811+0000] {logging_mixin.py:190} INFO - Validation successful. Found 1615 order records.
[2025-03-12T08:09:14.813+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-12T08:09:14.840+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T08:09:14.842+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weekly_category_analysis, task_id=orders, run_id=manual__2025-03-12T08:08:41.718880+00:00, execution_date=20250312T080841, start_date=20250312T080913, end_date=20250312T080914
[2025-03-12T08:09:14.912+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-12T08:09:14.913+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-12T08:09:14.917+0000] {logging_mixin.py:190} INFO - Dag name:weekly_category_analysis queued_at:2025-03-12 08:08:41.799977+00:00
[2025-03-12T08:09:14.920+0000] {logging_mixin.py:190} INFO - Task hostname:fc342882eb4f operator:PythonOperator
[2025-03-12T08:09:14.965+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-12T08:09:15.107+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-12T08:09:15.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
