[2025-03-10T07:34:27.655+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T07:34:27.779+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_all_tables.customers manual__2025-03-10T07:34:04.263360+00:00 [queued]>
[2025-03-10T07:34:27.949+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_all_tables.customers manual__2025-03-10T07:34:04.263360+00:00 [queued]>
[2025-03-10T07:34:27.992+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T07:34:28.882+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): customers> on 2025-03-10 07:34:04.263360+00:00
[2025-03-10T07:34:28.948+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T07:34:28.979+0000] {standard_task_runner.py:72} INFO - Started process 3519 to run task
[2025-03-10T07:34:29.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'validate_all_tables', 'customers', 'manual__2025-03-10T07:34:04.263360+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/validate_all_tables_dag.py', '--cfg-path', '/tmp/tmpuvipxq2b']
[2025-03-10T07:34:29.029+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask customers
[2025-03-10T07:34:29.732+0000] {task_command.py:467} INFO - Running <TaskInstance: validate_all_tables.customers manual__2025-03-10T07:34:04.263360+00:00 [running]> on host efacfdd0be48
[2025-03-10T07:34:30.927+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_all_tables' AIRFLOW_CTX_TASK_ID='customers' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T07:34:04.263360+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T07:34:04.263360+00:00'
[2025-03-10T07:34:30.934+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T07:34:30.944+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T07:34:30.946+0000] {logging_mixin.py:190} INFO - Current task name:customers state:running start_date:2025-03-10 07:34:27.817900+00:00
[2025-03-10T07:34:30.949+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables and current dag run status:running
[2025-03-10T07:34:30.967+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T07:34:31.231+0000] {logging_mixin.py:190} INFO - Customers validation and cleaning successful
[2025-03-10T07:34:31.241+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-10T07:34:31.317+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T07:34:31.363+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=validate_all_tables, task_id=customers, run_id=manual__2025-03-10T07:34:04.263360+00:00, execution_date=20250310T073404, start_date=20250310T073427, end_date=20250310T073431
[2025-03-10T07:34:31.776+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-10T07:34:31.780+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-10T07:34:31.790+0000] {logging_mixin.py:190} INFO - Dag name:validate_all_tables queued_at:2025-03-10 07:34:04.333514+00:00
[2025-03-10T07:34:31.792+0000] {logging_mixin.py:190} INFO - Task hostname:efacfdd0be48 operator:PythonOperator
[2025-03-10T07:34:31.914+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-10T07:34:32.117+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-10T07:34:32.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
